name: Pipeline

on: [push]
env:
  APPLICATION_NAME: app2
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python environment
      uses: actions/setup-python@v2
      with: 
          python-version: '3.8'
    - name: Install requirements
      run: pip install --quiet --requirement requirements.txt
    - name: Lint code
    
       
    - name: Run unit tests
      run: |
        python -m unittest --verbose --failfast
